export type ValidPaths =
  | "/"
  | "/about"
  | "/events"
  | "/sluzby/kompletni-priprava-na-porod-a-pece-v-tehotenstvi"
  | "/sluzby/pece-v-sestinedeli"
  | "/sluzby/laktacni-poradenstvi"
  | "/sluzby/tehotenske-a-rebozo-masaze"
  | "/sluzby/individualni-funkcni-trenink"
  | "/sluzby/bylinna-naparka"
  | "/sluzby/spinning-babies"
  | "/sluzby/zpracovani-placenty"
  | "/sluzby/ritualy"
  | "/kurzy-a-workshopy/predporodni-kurzy"
  | "/kurzy-a-workshopy/zazitkovy-predporodni-kurz"
  | "/kurzy-a-workshopy/fyzicka-priprava-na-porod"
  | "/kurzy-a-workshopy/kurz-posilovani-stredu-tela-a-panevniho-dna";
